/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as icoContractSol from "./IcoContract.sol";
export * as tokenSol from "./Token.sol";
export { AdminManager__factory } from "./AdminManager__factory";
export { MockPriceFeed__factory } from "./MockPriceFeed__factory";
export { TokenStaking__factory } from "./TokenStaking__factory";
