/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as icoContractSol from "./IcoContract.sol";
export type { icoContractSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { AdminManager } from "./AdminManager";
export type { MockPriceFeed } from "./MockPriceFeed";
export type { TokenStaking } from "./TokenStaking";
