/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AggregatorV3Interface } from "./AggregatorV3Interface";
export type { ICOContract } from "./ICOContract";
export type { IERC20 } from "./IERC20";
